class InputTeams:

    def __init__(self):
        self.validInputTeams = {
            "natus-vincere",
            "natus vincere",
            "navi",
            "gambit",
            "g2",
            "heroic",
            "furia",
            "copenhagen-flames",
            "cph-flames",
            "copenhagen flames",
            "cph flames",
            "vitality",
            "faze",
            "mouz",
            "mouz-sports",
            "mouz sports",
            "vp",
            "virtus.pro",
            "virtus pro",
            "virtus-pro",
            "tl",
            "liquid",
            "entropiq",
            "nip",
            "astralis",
            "eg",
            "evil geniuses",
            "evil-geniuses",
            "ence",
            "og",
            "big",
            "movistar riders",
            "movistar",
            "fiend",
            "spirit",
            "mad lions",
            "forze",
            "godsent",
            "skade",
            "lyngby-vikings",
            "lyngby vikings",
            "sinners",
            "complexity",
            "dignitas",
            "dbl-poney",
            "dbl poney",
            "fnatic",
            "party-astronauts",
            "party astronauts",
            "partynauts",
            "bnb",
            "bad news bears",
            "bad-news-bears",
            "extra-salt",
            "extra salt",
            "es",
            "triumph",
            "mythic",
            "pain",
            "teamone",
            "9z",
            "sharks",
            "00nation",
            "mibr",
            "anonymo",
            "endpoint",
            "ldlc",
            "k23",
            "singularity",
            "tyloo",
            "renegades"
        }

    def getIsValid(self, team: str):
        return team in self.validInputTeamsKJ0
